# Generated by Django 2.2 on 2019-04-01 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('published_date', models.DateTimeField(null=True)),
                ('slug', models.CharField(max_length=200)),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
    ]
