# Generated by Django 2.2 on 2019-04-04 04:29

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=martor.models.MartorField(),
        ),
    ]
